import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { 
  Calendar,
  Clock,
  DollarSign,
  Tag,
  FileText,
  Zap,
  RefreshCw,
  AlertCircle,
  Wand2
} from 'lucide-react';
import { useScheduledAuctions } from '@/hooks/useScheduledAuctions';
import { generateProductVariant } from '@/utils/dynamicAuctionGenerator';
import { toast } from 'sonner';

interface CreateScheduledAuctionProps {
  onSuccess: () => void;
  onCancel: () => void;
}

export const CreateScheduledAuction = ({ onSuccess, onCancel }: CreateScheduledAuctionProps) => {
  const { createScheduledAuction, isCreating } = useScheduledAuctions();

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    category: 'Perfumes',
    starting_bid: 25,
    duration_hours: 6,
    scheduled_date: '',
    scheduled_time: '',
    image_url: '',
  });

  const [isAutoGenerated, setIsAutoGenerated] = useState(false);

  const categories = [
    'Perfumes',
    'Vinos y Licores',
    'Electrónicos',
    'Navajas',
    'Relojes',
    'Joyas'
  ];

  const handleGenerateProduct = () => {
    try {
      const variant = generateProductVariant(formData.category);
      
      setFormData(prev => ({
        ...prev,
        title: variant.title,
        description: variant.description,
        image_url: variant.imageUrl,
        starting_bid: Math.max(15, Math.min(200, prev.starting_bid + Math.floor(Math.random() * 20) - 10)),
      }));

      setIsAutoGenerated(true);
      toast.success('🎯 Producto generado automáticamente');
    } catch (error) {
      toast.error('❌ Error al generar producto');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validation
    if (!formData.title.trim()) {
      toast.error('El título es requerido');
      return;
    }

    if (!formData.description.trim()) {
      toast.error('La descripción es requerida');
      return;
    }

    if (!formData.scheduled_date || !formData.scheduled_time) {
      toast.error('La fecha y hora de programación son requeridas');
      return;
    }

    // Combine date and time
    const scheduledDateTime = new Date(`${formData.scheduled_date}T${formData.scheduled_time}`);
    
    // Check if the datetime is in the future
    if (scheduledDateTime <= new Date()) {
      toast.error('La fecha y hora deben ser en el futuro');
      return;
    }

    try {
      await createScheduledAuction({
        title: formData.title,
        description: formData.description,
        category: formData.category,
        starting_bid: formData.starting_bid,
        duration_hours: formData.duration_hours,
        scheduled_publish_time: scheduledDateTime.toISOString(),
        image_url: formData.image_url,
      });

      toast.success('✅ Subasta programada creada exitosamente');
      onSuccess();
    } catch (error) {
      console.error('Error creating scheduled auction:', error);
      toast.error('❌ Error al crear la subasta programada');
    }
  };

  const getMinDateTime = () => {
    const now = new Date();
    now.setMinutes(now.getMinutes() + 10); // At least 10 minutes from now
    return now.toISOString().slice(0, 16);
  };

  const getDefaultDateTime = () => {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(12, 0, 0, 0);
    
    return {
      date: tomorrow.toISOString().slice(0, 10),
      time: '12:00'
    };
  };

  // Set default date/time on first render
  useState(() => {
    const defaultDateTime = getDefaultDateTime();
    setFormData(prev => ({
      ...prev,
      scheduled_date: defaultDateTime.date,
      scheduled_time: defaultDateTime.time
    }));
  });

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Auto-generate Section */}
      <Card className="border-dashed">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Wand2 className="h-5 w-5" />
            Generación Automática
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-muted-foreground">
                Genera automáticamente un producto único basado en la categoría seleccionada
              </p>
            </div>
            <Button
              type="button"
              onClick={handleGenerateProduct}
              variant="outline"
              className="flex items-center gap-2"
            >
              <Zap className="h-4 w-4" />
              Generar Producto
            </Button>
          </div>
          
          {isAutoGenerated && (
            <Alert>
              <Wand2 className="h-4 w-4" />
              <AlertDescription>
                Producto generado automáticamente. Puedes modificar los campos si es necesario.
              </AlertDescription>
            </Alert>
          )}
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left Column */}
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="category" className="flex items-center gap-2">
              <Tag className="h-4 w-4" />
              Categoría
            </Label>
            <Select
              value={formData.category}
              onValueChange={(value) => setFormData(prev => ({ ...prev, category: value }))}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {categories.map(category => (
                  <SelectItem key={category} value={category}>
                    {category}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="title" className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              Título
            </Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
              placeholder="Ej: iPhone 15 Pro Max - Decomisado en Arco de Seguridad"
              className={isAutoGenerated ? 'border-green-200 bg-green-50' : ''}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="description" className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              Descripción
            </Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              placeholder="Descripción detallada del producto..."
              rows={3}
              className={isAutoGenerated ? 'border-green-200 bg-green-50' : ''}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="image_url">URL de Imagen (Opcional)</Label>
            <Input
              id="image_url"
              type="url"
              value={formData.image_url}
              onChange={(e) => setFormData(prev => ({ ...prev, image_url: e.target.value }))}
              placeholder="https://ejemplo.com/imagen.jpg"
              className={isAutoGenerated ? 'border-green-200 bg-green-50' : ''}
            />
          </div>
        </div>

        {/* Right Column */}
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="starting_bid" className="flex items-center gap-2">
                <DollarSign className="h-4 w-4" />
                Precio Inicial
              </Label>
              <Input
                id="starting_bid"
                type="number"
                min="10"
                max="500"
                value={formData.starting_bid}
                onChange={(e) => setFormData(prev => ({ ...prev, starting_bid: Number(e.target.value) }))}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="duration_hours" className="flex items-center gap-2">
                <Clock className="h-4 w-4" />
                Duración (horas)
              </Label>
              <Input
                id="duration_hours"
                type="number"
                min="1"
                max="72"
                value={formData.duration_hours}
                onChange={(e) => setFormData(prev => ({ ...prev, duration_hours: Number(e.target.value) }))}
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="scheduled_date" className="flex items-center gap-2">
              <Calendar className="h-4 w-4" />
              Fecha de Programación
            </Label>
            <Input
              id="scheduled_date"
              type="date"
              value={formData.scheduled_date}
              onChange={(e) => setFormData(prev => ({ ...prev, scheduled_date: e.target.value }))}
              min={new Date().toISOString().slice(0, 10)}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="scheduled_time" className="flex items-center gap-2">
              <Clock className="h-4 w-4" />
              Hora de Programación
            </Label>
            <Input
              id="scheduled_time"
              type="time"
              value={formData.scheduled_time}
              onChange={(e) => setFormData(prev => ({ ...prev, scheduled_time: e.target.value }))}
            />
          </div>

          <Alert>
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              La subasta se publicará automáticamente en la fecha y hora especificadas.
            </AlertDescription>
          </Alert>
        </div>
      </div>

      {/* Preview */}
      {formData.title && (
        <Card className="bg-muted/30">
          <CardHeader>
            <CardTitle className="text-lg">Vista Previa</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              <h3 className="font-semibold">{formData.title}</h3>
              <p className="text-sm text-muted-foreground">{formData.description}</p>
              <div className="flex items-center gap-4 text-sm">
                <span className="flex items-center gap-1">
                  <Tag className="h-3 w-3" />
                  {formData.category}
                </span>
                <span className="flex items-center gap-1">
                  <DollarSign className="h-3 w-3" />
                  ${formData.starting_bid}
                </span>
                <span className="flex items-center gap-1">
                  <Clock className="h-3 w-3" />
                  {formData.duration_hours}h
                </span>
              </div>
              {formData.scheduled_date && formData.scheduled_time && (
                <p className="text-xs text-muted-foreground">
                  Se publicará el {new Date(`${formData.scheduled_date}T${formData.scheduled_time}`).toLocaleString()}
                </p>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Action Buttons */}
      <div className="flex justify-end gap-3 pt-4 border-t">
        <Button
          type="button"
          variant="outline"
          onClick={onCancel}
          disabled={isCreating}
        >
          Cancelar
        </Button>
        <Button
          type="submit"
          disabled={isCreating || !formData.title.trim() || !formData.description.trim()}
          className="bg-gradient-primary"
        >
          {isCreating ? (
            <>
              <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
              Creando...
            </>
          ) : (
            <>
              <Calendar className="h-4 w-4 mr-2" />
              Programar Subasta
            </>
          )}
        </Button>
      </div>
    </form>
  );
};
