// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxodekhmjymqyzudfbtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4b2Rla2htanltcXl6dWRmYnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzAwMjgsImV4cCI6MjA2OTYwNjAyOH0.8jceQn1atomnP0yrXR3N5m88ECDDXyKrdigmNp_X0rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});